# Generated by Django 3.0 on 2020-03-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionSalaryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_stipend', models.SmallIntegerField(choices=[(1, 'Tier 1 City'), (2, 'Tier 2 City'), (3, 'Tier 3 City'), (4, 'Tier 4 City'), (5, 'Tier 5 City'), (6, 'Tier 6 City')], default=1)),
                ('salary_step', models.SmallIntegerField(choices=[(1, 'Salary Step 1'), (2, 'Salary Step 2'), (3, 'Salary Step 3'), (4, 'Salary Step 4'), (5, 'Salary Step 5'), (6, 'Salary Step 6'), (7, 'Salary Step 7'), (8, 'Salary Step 8'), (9, 'Salary Step 9'), (10, 'Salary Step 10'), (11, 'Salary Step 11'), (12, 'Salary Step 12')], default=1)),
                ('leave_hours', models.SmallIntegerField(default=0)),
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employment.SalariedPosition')),
            ],
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount1', models.PositiveIntegerField(default=0)),
                ('amount_2', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(max_length=100)),
                ('part_1_awarded', models.BooleanField(default=False)),
                ('part_1_awarded_on', models.DateTimeField(default=None)),
                ('part_2_awarded', models.BooleanField(default=False)),
                ('part_2_awarded_on', models.DateTimeField(default=None)),
                ('related_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.PositionSalaryInfo')),
            ],
        ),
    ]
