version: "3.7"
services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    expose:
      - 15672
#  https://stackoverflow:
#    com/questions/54911090/serve-django-media-files-via-server_nginx-django-react-server_nginx-docker-compose:

  database:
    container_name: database
    image: "postgres"
    ports:
      - 5432:5432
    expose:
      - "5432"
    env_file:
      - database.env
    depends_on:
      - rabbitmq
#    volumes:
#      - database-data:/var/lib/postgresql/data/

  web:
    container_name: web
    hostname: apaxhr
    image: &web web
    build: app
    stdin_open: true
    tty: true
    volumes:
      - ./app:/app
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    expose:
      - "8000"
    depends_on:
      - database
      - rabbitmq
    command: python3 start_server.py dev

  redis:
    image: "redis:alpine"
    ports:
      - 6739:6739


  celery:
    image: *web
#    command: celery -A apaxhr worker --loglevel=info
    command: python3 start_server.py celery_worker
    volumes:
      - ./app:/app
    restart: on-failure
    env_file:
      - .env.dev
    depends_on:
      - redis
      - web
      - database
      - rabbitmq

  celery-beat:
    image: *web
#    command: celery -A tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#    command: celery -A apaxhr beat --loglevel=info  -S django_celery_beat.schedulers:DatabaseScheduler
    command: python3 start_server.py celery_beat
    volumes:
      - ./app:/app
    restart: on-failure
    env_file:
      - .env.dev
    depends_on:
      - redis
      - database
      - web
      - rabbitmq
      - celery