version: "3.7"
services:
#  rabbitmq:
#    container_name: rabbitmq
#    hostname: rabbitmq
#    image: rabbitmq:latest
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    expose:
#      - "5672"
#      - "15672"
#  https://stackoverflow:
#    com/questions/54911090/serve-django-media-files-via-server_nginx-django-react-server_nginx-docker-compose:
  database:
    container_name: database
    image: "postgres"
    ports:
      - 5432:5432
    expose:
      - "5432"
    env_file:
      - database.env
#    volumes:
#      - database-data:/var/lib/postgresql/data/

  web:
    container_name: web
    hostname: apaxhr
    build: app
    stdin_open: true
    tty: true
    volumes:
      - ./app:/web_root
    env_file:
      - .env.dev
    ports:
      - 8000:8000
    depends_on:
      - database
#      - rabbitmq
    command: python3 start_server.py prod_demo

#volumes:
#  database-data:
