# Generated by Django 3.0 on 2020-03-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Teaching', max_length=20)),
                ('other_title_note', models.CharField(default='other title note', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.SmallIntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='SalariedPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_start', models.DateTimeField(auto_now_add=True)),
                ('position_end', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('employment_status_note', models.TextField(default='no one has written about this position yet...', max_length=500)),
                ('title', models.CharField(choices=[('ap', 'Applicant'), ('tr', 'Trainee'), ('tch', 'Teacher'), ('fm', 'Faculty Manager'), ('am', 'Area Manager'), ('hr', 'HR Manager'), ('ht', 'Head Teacher'), ('tchmd', 'Teacher Management Director'), ('trd', 'Training Director'), ('rcd', 'Recruiting Director'), ('hrd', 'HR Director'), ('other', 'Other title'), ('dev', 'Developer')], default='tch', max_length=25)),
                ('department', models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.PROTECT, to='employment.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
