# Generated by Django 3.0 on 2020-03-27 03:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BiWeeklyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.SmallIntegerField(choices=[(1, 'Block 1 8:00 - 9:30'), (2, 'Block 2 9:30 - 11:15 '), (3, 'Block 3 14:00 - 15:30'), (4, 'Block 4 15:45 - 17:15'), (5, 'Block 5 17:30 - 19:00'), (6, 'Block 6 19:15 - 20:45')])),
                ('other_note', models.TextField(default='not an other course', max_length=85, verbose_name='Fill out this note if you have selected an other type class')),
                ('day1', models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday'), (8, 'Unused')], default=9)),
                ('day2', models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday'), (8, 'Unused')], default=9)),
                ('is_active', models.BooleanField(default=True)),
                ('class_title', models.CharField(max_length=25)),
                ('cm', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': 'Class Schedule',
            },
        ),
        migrations.CreateModel(
            name='CenterRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(default=-1, max_length=12, verbose_name='unique room')),
                ('note', models.TextField(max_length=250, verbose_name='Note any important details about a room here')),
            ],
            options={
                'verbose_name': '\u200bRoom',
            },
        ),
        migrations.CreateModel(
            name='CenterTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('preferred_room', models.SmallIntegerField(default=-1)),
            ],
            options={
                'verbose_name': '\u200bTeacher',
            },
        ),
        migrations.CreateModel(
            name='LearningCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('city', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherDailyTimesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blocks', models.PositiveSmallIntegerField(default=0)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.LearningCenter')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.CenterTeacher')),
            ],
        ),
        migrations.CreateModel(
            name='CenterWeeklyTimesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_end', models.DateField()),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('current_hours', django.contrib.postgres.fields.jsonb.JSONField(default={'hours not tallied yet': 0})),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.LearningCenter')),
            ],
        ),
        migrations.AddField(
            model_name='centerteacher',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.LearningCenter'),
        ),
    ]
