# Generated by Django 3.0 on 2020-03-27 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employment', '0001_initial'),
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerteacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='employment.SalariedPosition'),
        ),
        migrations.AddField(
            model_name='centerroom',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.LearningCenter'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.LearningCenter'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='day1_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_day1_teacher_set', to='centers.CenterTeacher'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='day2_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biweekly_day2_teacher_set', to='centers.CenterTeacher'),
        ),
        migrations.AddField(
            model_name='biweeklyclass',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.CenterRoom'),
        ),
        migrations.CreateModel(
            name='BiWeeklyClassDetailProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Class \u200b Detail',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('centers.biweeklyclass',),
        ),
        migrations.AddConstraint(
            model_name='teacherdailytimesheet',
            constraint=models.UniqueConstraint(fields=('teacher', 'center', 'date'), name='already logged hours, if needed delete teacherdailytimesheet manually from admin panel'),
        ),
        migrations.AddConstraint(
            model_name='centerteacher',
            constraint=models.UniqueConstraint(fields=('center', 'teacher'), name='teacher_constraint'),
        ),
        migrations.AddConstraint(
            model_name='centerroom',
            constraint=models.UniqueConstraint(fields=('center', 'name'), name='room_constraint'),
        ),
        migrations.AddConstraint(
            model_name='biweeklyclass',
            constraint=models.UniqueConstraint(fields=('center', 'room', 'day1', 'block'), name='day1 room conflict'),
        ),
        migrations.AddConstraint(
            model_name='biweeklyclass',
            constraint=models.UniqueConstraint(fields=('center', 'room', 'day2', 'block'), name='day2 room conflict'),
        ),
        migrations.AddConstraint(
            model_name='biweeklyclass',
            constraint=models.UniqueConstraint(fields=('center', 'block', 'day1', 'day1_teacher'), name='day1 teacher already booked'),
        ),
        migrations.AddConstraint(
            model_name='biweeklyclass',
            constraint=models.UniqueConstraint(fields=('center', 'block', 'day2', 'day2_teacher'), name='day2 teacher already booked'),
        ),
    ]
